### ISSUE TITLE
Question: why is pycparser listed in requirements.txt ?

### ISSUE THREAD

**Issue by Lucas-C** [Demindiro/agreper#14]
Hi!

Thank you for building & releasing this software as FLOSS 😊

I was checking this projects dependencies and I spotted `pycparser==2.21` among them:
https://github.com/Demindiro/agreper/blob/master/requirements.txt#L12

It does not seem used in the source code though.
Is it really required?

**Comment by Demindiro** [comment]
`pycparser` is an indirect dependency of `argon2-cffi`. Agreper does not directly depend on `pycparser`.

I generated `requirements.txt` with `pip3 freeze`, which also included a bunch of indirect dependencies. I'll remove those.

**Comment by Lucas-C** [comment]
Thank you for your answer
